---
title: PHOTORAMA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  test:
    title: test
    output: true
email: ''
description: Photo Journal
url: https://giorgosn.github.io
baseurl: "/photorama"
facebook_username: ''
twitter_username: ''
instagram_username: ''
github_username: ''
deviantart_username: ''
flickr_username: ''
discus_shortname: ''
share: true
owner:
  name: photorama
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template
comments:
  provider: disqus
  disqus:
    short_name: ''
nav:
- GALLERY: https://giorgosn.github.io/photorama/gallery/
- JOURNAL: https://giorgosn.github.io/photorama/journal/
- ABOUT: https://giorgosn.github.io/photorama/about/
translations:
  permalink: "/404.html"
destination: "./_site"
port: 4000
markdown: kramdown
highlighter: rouge
permalink: "/journal/:title/"
paginate: 5
paginate_path: "/journal/page:num/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems:
- jekyll-paginate
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
sitemap:
  file: "/sitemap.xml"
  exclude:
  - "/atom.xml"
  - "/feed.xml"
  - "/feed/index.xml"
  include_posts:
  - "/writing/"
  change_frequency_name: change_frequency
  priority_name: priority
